### ISSUE TITLE
Add check for correct data type

### ISSUE THREAD

**Issue by darylhjd** [Lim-Shi-Han/Self-directed-projects#1]
I'm gonna be big brain and enter "a" for all these inputs.

https://github.com/Lim-Shi-Han/Self-directed-projects/blob/a345524ae411820f7a04ed8dc0f8267b9d30c8ba/Calendar%20(date%20to%20day%20converter).py#L3-L7

**Comment by Lim-Shi-Han** [comment]
True I should probably implement checks! This was done before entering NTU so it might be a bit less polished!
